# fly.toml app configuration for Wingman Unified Server (Cloud Mode)
# Deploy with: fly deploy --config packages/relay-server/fly.toml

app = 'wingman-tunnel'
primary_region = 'iad'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[experimental]
  auto_rollback = true

[build]

[env]
  NODE_ENV = 'production'
  PORT = '8787'
  HOST = '0.0.0.0'
  # Enable cloud tunnel mode
  TUNNEL_MODE = 'cloud'
  # Base URL for generating tunnel URLs
  TUNNEL_BASE_URL = 'wingmanux.com'

[[services]]
  protocol = 'tcp'
  internal_port = 8787
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

  [[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '30s'

  [[services.http_checks]]
    interval = '30s'
    timeout = '3s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = false

    [services.http_checks.headers]
      Accept = 'application/json'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2