# fly.toml app configuration file generated for wingman-tunnel on 2025-08-20T20:56:22-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wingman-tunnel'
primary_region = 'den'

[build]
  dockerfile = "Dockerfile.standalone"

[http_service]
  internal_port = 9876
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
