# fly.toml app configuration file generated for wingman-tunnel-long-mountain-8219 on 2025-08-22T07:13:22-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wingman-tunnel'
primary_region = 'iad'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '9876'

[[services]]
  protocol = 'tcp'
  internal_port = 9876
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '30s'

  [[services.http_checks]]
    interval = '30s'
    timeout = '3s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = false

    [services.http_checks.headers]
      Accept = 'application/json'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
