# Tunnel client configuration for Fly.io
app = 'wingman-tunnel-client'
primary_region = 'iad'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[build]

[env]
  NODE_ENV = 'production'
  TUNNEL_SERVER_URL = 'https://wingman-tunnel.fly.dev'
  TARGET_APP_URL = 'https://wingman-test-app.fly.dev'
  SESSION_ID = 'test-tunnel'

# No services block needed - this is an outbound-only WebSocket client

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1