# fly.toml for Wingman App (Frontend)
# Deploy with: fly deploy --config packages/wingman-app/fly.toml

app = 'wingman-app'
primary_region = 'iad'
kill_signal = 'SIGTERM'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'packages/wingman-app/Dockerfile'
  [build.args]
    VITE_API_URL = 'https://wingman-tunnel.fly.dev'

[env]
  PORT = '8080'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 800

  [[services.http_checks]]
    interval = '30s'
    timeout = '3s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'
    protocol = 'http'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1