# fly.toml app configuration for Wingman App (Frontend)

app = 'wingman-app'
primary_region = 'iad'
kill_signal = 'SIGTERM'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

# Build section removed - specify dockerfile via CLI

[env]
  # Frontend served by nginx, no custom env needed

[[services]]
  protocol = 'tcp'
  internal_port = 80
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'

  [[services.http_checks]]
    interval = '30s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1