# fly.toml app configuration file generated for wingman-app-white-glade-6950 on 2025-08-25T16:54:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wingman-app-white-glade-6950'
primary_region = 'den'

[build]
  dockerfile = 'packages/webapp/Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
